language: elixir
elixir: 1.7.3
otp_release: 21.3.8
cache:
  directories:
  - _build
  - deps
deploy:
  provider: heroku
  app: slackacuse
  skip_cleanup: true
  api_key:
    secure: ZGit258PBtJyNGWWGGmjLHC/Bv7o7vq6S9+xj1WdE3v1X2oOwuDa1XV0mrVIuZEvmjsczz3i5btlDt54GDX1lTfHP5rJqI9GfulpBAJ3VHkr9dwLE41pWsVbEIG30BBoU35eLqGWjFPo/ZLv2z6eIMOLyVTPf53h+Kwlc1DUEzY9MkuFlVwSeS0+YNRVHOjkSCxCjhyKyJFX8hzDkl/fBk4BQ3vm7X3qwiVeCyTmQvbz4zHesDwlznOpiPg0vHCQLpb1FK91Ck/nIyIDZlgIPQQArnraMPRwITm3DzMz9l5JozDRQdKpJXTNElvjlgywaicvMVyA2GCoM0YWMj9hc6/zn8YHwuMUZM+zthznEyCluiFd+HqfXVqdrd1WLEJwMsnkHxXjQJjPWG1qGCPKevyKfNhXNGhtTMHS1NM0A9vN2k1fuYOJ5pCQqVLkt6e/5MfyWzifS3/NXyug0hN4uilUHLeb2DaA5EH6iPNqjAYOSRwd0fpFPiinBOI0s1kKKoPa31n7dTSF2vhQ9PFdoA31ZUfvqNLvDussqtEhyTPoQnJ9+gtyYjLF5Np1uS5azsRZ9N/OA4GlVHhlck2qMQ0hrwarhuIbpDbBWpjMsD+XMLjZuLXMv74CNn8XY3HBxwm4iK7y+JRvqToiALkRRzqTKdMvleAJmBapYzf85G4=
